[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./" }]

[invariant]
runs = 256
depth = 500
shrink_run_limit = 5000
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
